### ISSUE TITLE
Translations for new release v10.0.0

### ISSUE THREAD

**Issue by fin-ger** [deinstapel/cpupower#160]
`cpupower` is on the verge to release a new version `10.0.0` with support for AMD Ryzen and Gnome 40. In order to provide a smooth upgrade path I would like to ask our translators to take the [`template.pot`](https://github.com/martin31821/cpupower/blob/master/locale/template.pot) file and update the translations. @MarekPikula @honza-kasik @AlexGluck @amivaleo @Faenriis @LaurentTreguier @uno20001

Thank you for your help!

@martin31821 We can release once a majority of translations have landed in master.

 - [x] Czech
 - [x] French
 - [x] German
 - [ ] Hungarian
 - [x] Italian
 - [x] Polish
 - [ ] Russian
 - [ ] Serbian
 - [ ] Turkish

**Comment by amivaleo** [comment]
Am I a bad person if I submit the updated file here instead of using a pull request? 👀️

[it_IT.zip](https://github.com/martin31821/cpupower/files/7242155/it_IT.zip)

**Comment by fin-ger** [comment]
> Am I a bad person if I submit the updated file here instead of using a pull request?

No, that's perfectly fine! Thank you so much for your contribution!

**Comment by MarekPikula** [comment]
Hi there! Nice work with update to Gnome 40. May I suggest to make serialized profile names translatable? (ie. schemas/org.gnome.shell.extensions.cpupower.gschema.xml:4).

**Comment by fin-ger** [comment]
> May I suggest to make serialized profile names translatable? (ie. schemas/org.gnome.shell.extensions.cpupower.gschema.xml:4).

Sounds reasonable. However, I would postpone this to the next update to not further delay the Gnome 40 release. I will add a tracking issue for this.
