### ISSUE TITLE
Incompatible with Gnome 40 (Debian bookworm)

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [deinstapel/cpupower#170]
As of yesterday, the (more or less daily) update od Debian testing led Gnome to deem `cpupower` *incompatible* with the installed version of Gnome. So says the Gnome extensions page. #151  annotated.

Ouch...

**Comment by prakashpkb** [comment]
after i update the to ubuntu 21.10 and gnome version 40.4.0 it shows me incompatible.

**Comment by fin-ger** [comment]
Yes, the new release is not allowed to be published on Gnome Extensions. Use the manual installation method of the README to update to a version supporting Gnome 40. I'll may look into creating a PPA and copr in the near future. For now, you will have to use the manual installation methods.

Also, if anyone is interested in packaging this extension as RPM or DEB, please feel free to do so. I'm currently quite annoyed by the Gnome extension administrators and currently have little motivation working on this...

**Comment by prakashpkb** [comment]
> Yes, the new release is not allowed to be published on Gnome Extensions. Use the manual installation method of the README to update to a version supporting Gnome 40. I'll may look into creating a PPA and copr in the near future. For now, you will have to use the manual installation methods.
> 
> Also, if anyone is interested in packaging this extension as RPM or DEB, please feel free to do so. I'm currently quite annoyed by the Gnome extension administrators and currently have little motivation working on this...

./scripts/update-translations.sh: line 9: /usr/bin/msgfmt: No such file or directory
make: *** [Makefile:29: build] Error 127


Showing Error

**Comment by fin-ger** [comment]
You do not have `gettext` installed. Please refer to https://github.com/deinstapel/cpupower#installing-via-makefile

However, if you are not sure what you are doing there, please consider not continuing here. Doing an error here can potentially open backdoors for attackers to run malicious software on your PC. I'm afraid there is currently no convenient way to install this extension.

**Comment by vega-d** [comment]
upgraded to ubuntu 21.10, can confirm it's broken

**Comment by fin-ger** [comment]
As already mentioned. Gnome 40 support is included in version 10.0.0. This version is not allowed to be published on extensions.gnome.org by the Gnome extension administrators due to us still supporting older version of Gnome. You will have to install it manually, either [the zip in the release section](https://github.com/deinstapel/cpupower/releases/tag/v10.0.0) or the [manual installation method](https://github.com/deinstapel/cpupower#installing-for-another-admin-user) described in the README.

As the requirements for a Gnome 40 release have been communicated to us after we finished all testing and development of our Gnome 40 release, we currently have little resources left to redo all the work. Plus, we would have to drop support for all other Gnome releases, which is currently not even in my own interest as I'm still relying on Gnome 3.38 for stability reasons.

**Comment by peter-kehl** [comment]
For Arch/Manjaro Linux, see a related/duplicate #174.

**Comment by fin-ger** [comment]
I am currently trying to push a successfully built and tested debian package to a launchpad ppa, but I just cannot figure out why the package upload is failing. If anyone has experience with this, please consider helping out.

The distribution package for debian/ubuntu can be built be cloning this repo and running:

```
$ make package dist
```

The files will be placed in `dist/deb/`. However, when trying to upload the package to a ppa it fails with `Unknown release buster`. I just can't figure out how to fix this.

```
$ dput ppa:fin1ger/cpupower dist/deb/gnome-shell-extension-cpupower_10.0.0-1_amd64.changes
Uploading gnome-shell-extension-cpupower using ftp to ppa (host: ppa.launchpad.net; directory: ~fin1ger/cpupower)
running supported-distribution: check whether the target distribution is currently supported (using distro-info)
{'allowed': ['release'], 'known': ['release', 'proposed', 'updates', 'backports', 'security']}
Unknown release buster
```

Thanks for any hints.

**Comment by fin-ger** [comment]
This extensions is now available via a PPA and can be installed on debian 11, ubuntu bionic, ubuntu focal, and ubuntu hirsute. It is also installable on other releases of debian and ubuntu, however Gnome 41 support is not ready yet.

**Comment by fin-ger** [comment]
Oh, forgot to mention. Please consult the Readme for detailed installation instructions.

**Comment by Barraguesh** [comment]
Would be nice to include a disclaimer that GNOME 41 isn't supported for now.

**Comment by fin-ger** [comment]
@barraguesh I'm happy to add such a disclaimer. Where would you expect this? The Readme states GNOME 40, and the GNOME extensions site shows this extension as incompatible with GNOME 41.

**Comment by Barraguesh** [comment]
@fin-ger I would say inside the installation instructions of Fedora and any distro that might be the most up-to-date regarding GNOME. Like "Please note, this extension supports versions of GNOME up to 40".

**Comment by fin-ger** [comment]
Done. I added a note to all installation methods, I expect all the distros to eventually ship Gnome 41. I don't know if I'll be fast enough to ship a Gnome 41 release before all distros ship Gnome 41.

As this issue remains unanswered whether actually Gnome 41 is affected (title still states Gnome 40, no response from author), I will close this issue in favor of #174. Thank you for your hints!
